#pragma once


namespace Client
{
	enum LEVEL { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_RACE, LEVEL_TEST, LEVEL_END };
	enum COLLIDER_ID { COL_PAWN, COL_MONSTER, COL_BLOCK, COL_PBULLET, COL_MBULLET, COL_END };
}
