#pragma once


namespace Client
{
	enum LEVEL { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_RACE, LEVEL_TEST, LEVEL_END };
	enum COLLIDER_GROUP { CG_PAWN, CG_MONSTER, CG_BLOCK, CG_PBULLET, CG_MBULLET, CG_END };

	enum COLLIDER_ID {
		CI_PLAYER,															// 플레이어
		CI_MON_HEAD, CI_MON_BODY,											// 몬스터
		CI_LOVERBOY, CI_CHAINGUN, CI_DISPENSOR_SHELL, CI_DISPENSOR_GRENADE, // 플레이어 무기
		CI_BLOCK_COMMON, CI_BLOCK_INVISIBLE,								// 블럭들
		CI_MONSTER_BULLET
	};
}
