#pragma once


namespace Client
{
	enum LEVEL { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_RACEFIRST, LEVEL_RACESECOND, LEVEL_RACETHIRD, LEVEL_BOSS, LEVEL_INDOOR, LEVEL_OUTDOOR, LEVEL_END };
	enum COLLIDER_GROUP { CG_PAWN, CG_PAWN_PRE, CG_MONSTER, CG_MONSTER_BODY, CG_MONSTER_HEAD, CG_BOSS, CG_BLOCK, CG_INTERACTIVE, CG_ITEM, CG_PBULLET, CG_MBULLET, CG_TRIGGER, CG_END };

	enum COLLIDER_ID {
		CI_PLAYER_START,																			// 플레이어
		CI_PLAYER, CI_PLAYER_PRE,
		CI_PLAYER_END,

		CI_MONBODY_START,                                                                            // 몬스터 몸통
		CI_MON_BODY, CI_MONSTER_MECHSECT, CI_MONSTER_WENTEKO, CI_MONSTER_ARCHANGELBODY,
		CI_MONBODY_END,

		CI_MONHEAD_START,																			// 몬스터 머리(약점)
		CI_MON_HEAD,
		CI_MONHEAD_END,

		CI_WEAPON_START,																			// 플레이어 무기
		CI_LOVERBOY, CI_CHAINGUN, CI_DISPENSOR_SHELL, CI_DISPENSOR_GRENADE,CI_MISSILE,
		CI_WEAPON_END,

		CI_ITEM_START,
		CI_ITEM_HEALKIT, CI_ITEM_ARMOR_PIECE, CI_ITEM_ARMOR_FULL,									// 아이템
		CI_ITEM_CARDKEY,
		CI_ITEM_AMMO_CHAINGUN, CI_ITEM_AMMO_DISPENSER_SCATTER, CI_ITEM_AMMO_DISPENSER_CANNON, CI_ITEM_AMMO_LOVERBOY,
		CI_ITEM_END,

		CI_BLOCK_START,																				// 블럭들
		CI_BLOCK_COMMON, CI_BLOCK_INVISIBLE,
		CI_BLOCK_END,

		CI_INTERACTIVE_START,																		// 플레이어 상호작용 옵젝
		CI_INTERACTIVE_LAVA, CI_INTERACTIVE_LADDER, CI_INTERACTIVE_PICTURE, CI_INTERACTIVE_SECURITY, CI_INTERACTIVE_TRASHCAN,
		CI_INTERACTIVE_GARBAGEBAG, CI_INTERACTIVE_FIREPLUG, CI_INTERACTIVE_DOOR,
		CI_INTERACTIVE_END,

		CI_MBULLET_START,																			// 몬스터 투사체
		CI_MONSTER_BULLET, CI_MONSTER_SHOTGUNNER, CI_MONSTER_CULTIST, CI_MONSTER_GREATER, CI_MONSTER_DEACON, CI_MONSTER_NUKEMUTANT, 
		CI_MONSTER_ARCHANGEL,
		
		CI_BOSS_GUIDBULLET, CI_BOSS_FIRE, CI_BOSS_BULLET, CI_BOSS_JUMP, CI_BOSS_TANGTANG,
		CI_MBULLET_END,

		CI_TRIGGER,                                                                                // 트리거 ( 조건문 안들어가게 하기 위해서 만든 이넘 )
		CI_PICKING_RAY,

		CI_END
	};

#define CI_PLAYER( ID )		(CI_PLAYER_START < ID && CI_PLAYER_END > ID )
#define CI_MONBODY( ID )	(CI_MONBODY_START < ID && CI_MONBODY_END > ID )
#define CI_MONHEAD( ID )	(CI_MONHEAD_START < ID && CI_MONHEAD_END > ID )
#define CI_WEAPON( ID )		(CI_WEAPON_START < ID && CI_WEAPON_END > ID )
#define CI_BLOCK( ID )		(CI_BLOCK_START < ID && CI_BLOCK_END > ID )
#define CI_MBULLET( ID )	(CI_MBULLET_START < ID && CI_MBULLET_END > ID )
#define CI_INTERACTIVE_START( ID ) (CI_INTERACTIVE_START < ID && CI_INTERACTIVE_END > ID )
#define CI_ITEM( ID )        (CI_ITEM_START < ID && CI_ITEM_END > ID)

	enum UI_DEPTH
	{
		UI_PRIORITY,
		UI_EFFECT,
		UI_DECO,
		UI_FONT,
		UI_BUTTON,
		UI_HUD,
		UI_PLAYER,
		UI_OBJECT_HUD,
		UI_BACKGROUND,
		UI_CAMERA = 9999 // 무조건 가장 큰 숫자일 것 = 렌더러 최우선순위
	};

}
